### ISSUE TITLE
Add a link to this project in the WSAPM project

### ISSUE THREAD

**Issue by DecaTec** [Seji64/LoggedOnUsersPlugin#1]
Not a real issue here: I'm the developer of Windows Server Advanced Power Management (https://github.com/DecaTec/Wsapm).
Great to see others creating plugins for WSAPM. Just wanted to ask if I might add a link to your plugin on the WSAPM repository and on my website ([german](https://decatec.de/software/windows-server-advanced-power-management/)/[english](https://decatec.de/software/windows-server-advanced-power-management_en/)).

**Comment by Seji64** [comment]
Hi, wir können uns auch gern auf deutsch unterhalten ;-)

Klar kannst das Plugin gern auf die Webseite packen.

Gruß Seji

**Comment by DecaTec** [comment]
Servus, habe ich mir schon fest gedacht ;)
Alles klar, Links sind eingefügt. Wenn du eine neue Version veröffentlichen solltest, kannst du mich ja kurz kontaktieren.

Gruß,
Jan
